#!/bin/sh
a=0
p=$4
while [ $a -lt $5 ] ; do
	output=`./"$1" "$2" "$3" "../facebook_combined.txt" "$p" | grep -v "Fault"`
	if [ -n "$output" ] ; then
		echo $output;
	fi
	sleep 1
	a=`expr $a '+' 1`
	p=`expr $p '*' 2`
done
